import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../i18n";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} scrollbar-hide h-full scroll-smooth antialiased`}
    >
      <head>
        <link rel="icon" type="image/svg+xml" href="/me.jpg" />
      </head>
      <body className="flex min-h-full flex-col select-none">
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
